version: 2
jobs:
  jdk8:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
      - image: circleci/postgres:9.6.3-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
      
    steps:
      - checkout
      - run: echo "Wahhoi CircleCI!"
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:5432 -timeout 120s
            
      - run: mvn dependency:go-offline
      - run: mvn package
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/demo-java-spring-0.0.1-SNAPSHOT.jar

          
  jdk10:
    docker:
      - image: circleci/openjdk:10-jdk-browsers
      - image: circleci/postgres:9.6.3-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
      
    steps:
      - checkout
      - run: echo "Wahhoi CircleCI!"
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:5432 -timeout 120s
            
      - run: mvn dependency:go-offline
      - run: mvn package
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/demo-java-spring-0.0.1-SNAPSHOT.jar

          
  jdk11:
    docker:
      - image: circleci/openjdk:11-jdk-browsers
      - image: circleci/postgres:9.6.3-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
      
    steps:
      - checkout
      - run: echo "Wahhoi CircleCI!"
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:5432 -timeout 120s
            
      - run: mvn dependency:go-offline
      - run: mvn package
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/demo-java-spring-0.0.1-SNAPSHOT.jar

workflows:
  version: 2
  build:
    jobs:
      - jdk8
      - jdk10
      - jdk11